feature/Adds new HTTP conflict code.
Mindera/skeletoid pull request #100
Opened 2019-06-03 17:37 UTC by bruno-garces

2019-06-03 17:50 UTC, djrsousa approved these changes

2019-06-03 21:31 UTC, neteinstein requested changes
Maybe we should add them all:


400 | Bad Request | [RFC7231, Section 6.5.1]
401 | Unauthorized | [RFC7235, Section 3.1]
402 | Payment Required | [RFC7231, Section 6.5.2]
403 | Forbidden | [RFC7231, Section 6.5.3]
404 | Not Found | [RFC7231, Section 6.5.4]
405 | Method Not Allowed | [RFC7231, Section 6.5.5]
406 | Not Acceptable | [RFC7231, Section 6.5.6]
407 | Proxy Authentication Required | [RFC7235, Section 3.2]
408 | Request Timeout | [RFC7231, Section 6.5.7]
409 | Conflict | [RFC7231, Section 6.5.8]
410 | Gone | [RFC7231, Section 6.5.9]
411 | Length Required | [RFC7231, Section 6.5.10]
412 | Precondition Failed | [RFC7232, Section 4.2][RFC8144, Section 3.2]
413 | Payload Too Large | [RFC7231, Section 6.5.11]
414 | URI Too Long | [RFC7231, Section 6.5.12]
415 | Unsupported Media Type | [RFC7231, Section 6.5.13][RFC7694, Section 3]
416 | Range Not Satisfiable | [RFC7233, Section 4.4]
417 | Expectation Failed | [RFC7231, Section 6.5.14]

421 | Misdirected Request | [RFC7540, Section 9.1.2]
422 | Unprocessable Entity | [RFC4918]
423 | Locked | [RFC4918]
424 | Failed Dependency | [RFC4918]
425 | Too Early | [RFC8470]
426 | Upgrade Required | [RFC7231, Section 6.5.15]

428 | Precondition Required | [RFC6585]
429 | Too Many Requests | [RFC6585]

431 | Request Header Fields Too Large | [RFC6585]

451 | Unavailable For Legal Reasons | [RFC7725]

500 | Internal Server Error | [RFC7231, Section 6.6.1]
501 | Not Implemented | [RFC7231, Section 6.6.2]
502 | Bad Gateway | [RFC7231, Section 6.6.3]
503 | Service Unavailable | [RFC7231, Section 6.6.4]
504 | Gateway Timeout | [RFC7231, Section 6.6.5]
505 | HTTP Version Not Supported | [RFC7231, Section 6.6.6]
506 | Variant Also Negotiates | [RFC2295]
507 | Insufficient Storage | [RFC4918]
508 | Loop Detected | [RFC5842]

510 | Not Extended | [RFC2774]
511 | Network Authentication Required | [RFC6585]

2019-06-04 08:52 UTC, ritatferreira approved these changes

2019-06-05 11:06 UTC, bruno-garces commented
> Maybe we should add them all:
> 
> 400 | Bad Request | [RFC7231, Section 6.5.1]
> 401 | Unauthorized | [RFC7235, Section 3.1]
> 402 | Payment Required | [RFC7231, Section 6.5.2]
> 403 | Forbidden | [RFC7231, Section 6.5.3]
> 404 | Not Found | [RFC7231, Section 6.5.4]
> 405 | Method Not Allowed | [RFC7231, Section 6.5.5]
> 406 | Not Acceptable | [RFC7231, Section 6.5.6]
> 407 | Proxy Authentication Required | [RFC7235, Section 3.2]
> 408 | Request Timeout | [RFC7231, Section 6.5.7]
> 409 | Conflict | [RFC7231, Section 6.5.8]
> 410 | Gone | [RFC7231, Section 6.5.9]
> 411 | Length Required | [RFC7231, Section 6.5.10]
> 412 | Precondition Failed | [RFC7232, Section 4.2][RFC8144, Section 3.2]
> 413 | Payload Too Large | [RFC7231, Section 6.5.11]
> 414 | URI Too Long | [RFC7231, Section 6.5.12]
> 415 | Unsupported Media Type | [RFC7231, Section 6.5.13][RFC7694, Section 3]
> 416 | Range Not Satisfiable | [RFC7233, Section 4.4]
> 417 | Expectation Failed | [RFC7231, Section 6.5.14]
> 
> 421 | Misdirected Request | [RFC7540, Section 9.1.2]
> 422 | Unprocessable Entity | [RFC4918]
> 423 | Locked | [RFC4918]
> 424 | Failed Dependency | [RFC4918]
> 425 | Too Early | [RFC8470]
> 426 | Upgrade Required | [RFC7231, Section 6.5.15]
> 
> 428 | Precondition Required | [RFC6585]
> 429 | Too Many Requests | [RFC6585]
> 
> 431 | Request Header Fields Too Large | [RFC6585]
> 
> 451 | Unavailable For Legal Reasons | [RFC7725]
> 
> 500 | Internal Server Error | [RFC7231, Section 6.6.1]
> 501 | Not Implemented | [RFC7231, Section 6.6.2]
> 502 | Bad Gateway | [RFC7231, Section 6.6.3]
> 503 | Service Unavailable | [RFC7231, Section 6.6.4]
> 504 | Gateway Timeout | [RFC7231, Section 6.6.5]
> 505 | HTTP Version Not Supported | [RFC7231, Section 6.6.6]
> 506 | Variant Also Negotiates | [RFC2295]
> 507 | Insufficient Storage | [RFC4918]
> 508 | Loop Detected | [RFC5842]
> 
> 510 | Not Extended | [RFC2774]
> 511 | Network Authentication Required | [RFC6585]

2019-06-05 11:34 UTC, neteinstein approved these changes

2019-06-05 13:34 UTC, merged