Feature/AppRatingDialog
Mindera/skeletoid pull request #105
Opened 2019-06-26 15:33 UTC by ritatferreira

Implementation of the default rating dialog

HOW TO:

- Call the `init` without passing the callback
- Whenever `promptDialog` is called, a fragment manager should be passed
- The activity of the fragment manager should implement the `AppRatingDialogResponseCallback`

2019-06-26 15:59 UTC, neteinstein approved these changes

2019-06-26 16:42 UTC, joaocaseiro commented
Why is the AppRatingDialogCallback in the AppRatingInitializer a lateinit? Isn't it being used as a nullable anyway (doing checks against its initialisation in the promptDialog function)

2019-06-27 10:56 UTC, MajaTrzebiatowska commented
the build is failing ;(

`Task :apprating:compileQaKotlin FAILED
e: /home/travis/build/Mindera/skeletoid/apprating/src/main/java/com/mindera/skeletoid/apprating/AppRatingInitializer.kt: (65, 64): Smart cast to 'AppRatingDialogCallback' is impossible, because 'callback' is a mutable property that could have been changed by this time`

2019-06-27 18:27 UTC, neteinstein requested changes
e: /home/travis/build/Mindera/skeletoid/apprating/src/main/java/com/mindera/skeletoid/apprating/AppRatingInitializer.kt: (65, 64): Smart cast to 'AppRatingDialogCallback' is impossible, because 'callback' is a mutable property that could have been changed by this time

2019-07-01 10:45 UTC, bruno-garces approved these changes

2019-07-01 16:45 UTC, joaocaseiro approved these changes

2019-07-01 16:59 UTC, neteinstein approved these changes

2019-07-01 17:01 UTC, merged