Fix: Upgraded Skeletoid to be compatible with SDK and Tools latest versions
Mindera/skeletoid pull request #117
Opened 2019-10-17 17:12 UTC by neteinstein

If you use on an app:
```
compileSdkVersion = 29
buildToolsVersion = '29.0.0'
```

You would not be able to compile the project due to the `AbstractDialog` files show method conflicting with the SDK ones.

2019-10-17 18:01 UTC, Jmvcaseiro reviewed
I don't know who made them, but the first 6 commits are very good.

2019-10-18 09:02 UTC, ritatferreira requested changes

2019-10-18 09:02 UTC, ritatferreira commented on base/src/main/java/com/mindera/skeletoid/dialogs/AbstractDialogFragment.kt
> +    private fun onClick(state: DialogState) {
Is there a reason for this to be private instead of protected? We are using it in WR

2019-10-18 09:18 UTC, neteinstein commented on base/src/main/java/com/mindera/skeletoid/dialogs/AbstractDialogFragment.kt
> +    private fun onClick(state: DialogState) {
No reason, we'll revert it.

2019-10-18 10:30 UTC, ritatferreira approved these changes

2019-10-18 10:46 UTC, merged