Unit tests: Added to cover untested areas of code
Mindera/skeletoid pull request #143
Opened 2020-08-13 11:36 UTC by neteinstein

2021-01-26 23:07 UTC, neteinstein commented
@bruno-garces Since you are touching this, travis-ci.org is shuting down and moving to travis-ci.com

Can you please review this PR and check if anything is needed to migrate this pipeline?

2021-01-27 11:20 UTC, bruno-garces requested changes

2021-01-27 11:20 UTC, bruno-garces commented on rxjava/src/debug/kotlin/com/mindera/skeletoid/rxjava/schedulers/Schedulers.kt
> +    fun main(): Scheduler = io.reactivex.android.schedulers.AndroidSchedulers.mainThread()
```
io.reactivex.schedulers.Schedulers
```

Given that we have this import maybe we could either update `computation` and `io` removing the unnecessary full path or update `single` to be coherent with the other and remove the import.

2021-01-27 11:20 UTC, bruno-garces commented on rxjava/src/test/java/com/mindera/skeletoid/rxjava/CompletableExtensionsTest.kt
> +            .blockingGet()
There is no need to do `blockingGet`

```
Completable.fromAction { thread = currentThreadName() }
    .subscribeOnIO()
    .test()
    .assertNoErrors()
    .assertComplete()
```

2021-01-27 11:20 UTC, bruno-garces commented on rxjava/src/test/java/com/mindera/skeletoid/rxjava/CompletableExtensionsTest.kt
> +        Completable.fromAction { thread = Thread.currentThread().name }
We could have a small function that would return this

```
private fun currentThreadName(): String = Thread.currentThread().name
```

2021-01-27 11:20 UTC, bruno-garces commented on rxjava/src/test/java/com/mindera/skeletoid/rxjava/MaybeExtensionsTest.kt
> +            .blockingGet()
Same here

2021-01-27 11:20 UTC, bruno-garces commented on rxjava/src/test/java/com/mindera/skeletoid/rxjava/ObservableExtensionsTest.kt
> +        assertEquals(thread, Thread.currentThread().name) // To be fixed: read above
Consider change to the following

```
private fun currentThreadName(): String = Thread.currentThread().name

@Test
fun testObservableSubscribeOnIO() {
    Observable.just(1)
        .map { currentThreadName() }
        .subscribeOnIO()
        .test()
        .assertValueAt(0) { it == "main" }
        .assertValueCount(1)
        .assertNoErrors()
        .assertComplete()
}
```

2021-01-27 11:20 UTC, bruno-garces commented on rxjava/src/test/java/com/mindera/skeletoid/rxjava/SingleExtensionsTest.kt
> +        assertEquals(thread, "main") // To be fixed: read above
We could follow the same approach as explained before.

2021-01-28 17:36 UTC, bruno-garces approved these changes

2021-01-29 10:17 UTC, neteinstein commented
continuous-integration/travis-ci Expected — Waiting for status to be reported
Required

This will always be like this as it's the old travis.

Should we merge @bruno-garces ?

2021-01-29 10:24 UTC, bruno-garces commented
> continuous-integration/travis-ci Expected — Waiting for status to be reported
> Required
> 
> This will always be like this as it's the old travis.
> 
> Should we merge @bruno-garces ?

Do it

2021-01-29 10:30 UTC, merged