Feature - Added versioning utils
Mindera/skeletoid pull request #78
Opened 2019-02-06 17:20 UTC by neteinstein

2019-02-06 18:08 UTC, bruno-garces requested changes

2019-02-06 18:08 UTC, bruno-garces commented on base/src/main/java/com/mindera/skeletoid/utils/versioning/Versioning.kt
> +        return if (i < vals1.size && i < vals2.size) {
```suggestion
        return run {
            // compare first non-equal ordinal number
            if (i < vals1.size && i < vals2.size) {
                vals1[i].toInt().compareTo(vals2[i].toInt())
            } else {
                // the strings are equal or one string is a substring of the other
                // e.g. "1.2.3" = "1.2.3" or "1.2.3" < "1.2.3.4"
                vals1.size - vals2.size
            }
        }.sign
```

2019-02-06 18:08 UTC, bruno-garces commented on base/src/main/java/com/mindera/skeletoid/utils/versioning/Versioning.kt
> +    fun compareVersions(str1: String, str2: String): Int {
can we add unit tests?

2019-02-08 16:33 UTC, neteinstein commented on base/src/main/java/com/mindera/skeletoid/utils/versioning/Versioning.kt
> +    fun compareVersions(str1: String, str2: String): Int {
Added

2019-02-08 16:37 UTC, bruno-garces approved these changes

2019-02-08 17:01 UTC, merged