[WIP] Unit tests
Mindera/skeletoid pull request #97
Opened 2019-05-22 11:00 UTC by MajaTrzebiatowska

* Fixes jacoco integration to generate reports from all modules
* Adds unit test increasing the coverage to at least 42%

2019-05-22 11:29 UTC, neteinstein approved these changes
Hail Maya Queen of Skeletoid! 🙇‍♂️

2019-05-22 11:29 UTC, neteinstein commented on .travis.yml
> +  - ./gradlew createGlobalSkeletoidUnitTestReport
💪

2019-05-22 11:29 UTC, neteinstein commented on analytics-ga/src/main/java/com/mindera/skeletoid/analytics/appenders/GaAppender.kt
> +    private val LOG_TAG = "GAAppender"
maybe set as a const inside companion object

2019-05-22 11:29 UTC, neteinstein commented on base/src/main/java/com/mindera/skeletoid/logs/utils/ShareLogFilesUtils.java
> +                                String bodyText, String[] emails, File file) {
indentation :-)

2019-05-22 11:45 UTC, Jmvcaseiro commented on base/src/test/java/com/mindera/skeletoid/threads/threadpools/ThreadPoolExecutorUnitTest.java
> +    }
could this be removed?

2019-05-22 14:47 UTC, bruno-garces requested changes

2019-05-22 14:47 UTC, bruno-garces commented on analytics-firebase/src/main/java/com/mindera/skeletoid/analytics/appenders/FbAppender.kt
> +    override fun setUserID(userID: String) {
since we're on the verge of doing everything the right way, I'd suggest to rename this to `setUserId`

2019-05-22 14:47 UTC, bruno-garces commented on analytics-ga/src/main/java/com/mindera/skeletoid/analytics/appenders/GaAppender.kt
> +class GAAppender(private val configurationFileId: Int) : IAnalyticsAppender {
Shouldn't this be called `GaAppender` ?

2019-05-22 14:47 UTC, bruno-garces commented on analytics-ga/src/test/java/com/mindera/skeletoid/analytics/appenders/GAAppenderUnitTest.kt
>  class GAAppenderUnitTest {
`GaAppenderUnitTest` ?

2019-05-22 14:47 UTC, bruno-garces commented on base/src/main/java/com/mindera/skeletoid/network/Connectivity.kt
> +    fun isConnectedToWIFI(context: Context?): Boolean {
`isConnectedToWifi` maybe ?

2019-05-22 14:47 UTC, bruno-garces commented on base/src/main/java/com/mindera/skeletoid/network/Connectivity.kt
> +        val ni = cm?.activeNetworkInfo
can we have better var names ?

2019-05-22 14:47 UTC, bruno-garces commented on base/src/test/java/com/mindera/skeletoid/threads/threadpools/ThreadPoolExecutorUnitTest.java
> +//        verify(mock.toString());
can we delete this one?

2019-05-22 14:47 UTC, bruno-garces commented on base/src/test/java/com/mindera/skeletoid/utils/OptionalTest.kt
> +import org.junit.Assert.*
wildcard imports 😱

2019-05-22 15:04 UTC, neteinstein commented on analytics-firebase/src/main/java/com/mindera/skeletoid/analytics/appenders/FbAppender.kt
> +    override fun setUserID(userID: String) {
😂

2019-05-23 09:09 UTC, Jmvcaseiro commented on analytics-firebase/src/main/java/com/mindera/skeletoid/analytics/appenders/FbAppender.kt
> +    override fun setUserID(userID: String) {
🤦‍♂

2019-05-23 09:11 UTC, Jmvcaseiro commented on base/src/test/java/com/mindera/skeletoid/threads/threadpools/ThreadPoolExecutorUnitTest.java
> +//        verify(mock.toString());
#ifOnlySomeoneHadCommentedThisAlready 🤔

2019-05-28 12:46 UTC, djrsousa approved these changes

2019-05-28 14:24 UTC, pedro-belchior commented on base/src/main/java/com/mindera/skeletoid/generic/AndroidUtils.java
> -     * @return Label of the app, or App.
hmm typo ?

2019-05-29 08:37 UTC, pedro-belchior commented on base/src/test/java/com/mindera/skeletoid/logs/LOGUnitTest.java
> +        LOG.removeAppenders(context, null);
I think im missing something, shouldn't we be verifying or asserting something here ?

2019-05-29 09:17 UTC, bruno-garces approved these changes

2019-05-29 09:51 UTC, merged